apiVersion: v1
kind: LimitRange
metadata:
  name: code-executor-limits
  namespace: code-runner-env
spec:
  limits:
    - max:
        cpu: "200m"
        memory: "256Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      type: Container