apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted-app-sa
  namespace: code-runner-env
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: code-executor-pod-creator
  namespace: code-runner-env
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "pods/log"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-executor-binding
  namespace: code-runner-env
subjects:
  - kind: ServiceAccount
    name: restricted-app-sa
    namespace: code-runner-env
roleRef:
  kind: Role
  name: code-executor-pod-creator
  apiGroup: rbac.authorization.k8s.io